// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpkEKTPJau8v92UXwN_AkJELq4ft08-wU',
    appId: '1:621794686943:web:b9b6ac5890a02c7af6f66a',
    messagingSenderId: '621794686943',
    projectId: 'horas-v3-d8f04',
    authDomain: 'horas-v3-d8f04.firebaseapp.com',
    storageBucket: 'horas-v3-d8f04.firebasestorage.app',
    measurementId: 'G-6743LKYLLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU0b5p2nPIRi9SEz_0QFutl_tZQCa2YLg',
    appId: '1:621794686943:android:ad8819a624907373f6f66a',
    messagingSenderId: '621794686943',
    projectId: 'horas-v3-d8f04',
    storageBucket: 'horas-v3-d8f04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh-yIKBVauHzJRavhN1QwvJ3fGxsx3qSQ',
    appId: '1:621794686943:ios:1da4f7d15125e7b1f6f66a',
    messagingSenderId: '621794686943',
    projectId: 'horas-v3-d8f04',
    storageBucket: 'horas-v3-d8f04.firebasestorage.app',
    iosBundleId: 'br.com.aprendizadoflutter.horas.horasV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpkEKTPJau8v92UXwN_AkJELq4ft08-wU',
    appId: '1:621794686943:web:328417a088f3b402f6f66a',
    messagingSenderId: '621794686943',
    projectId: 'horas-v3-d8f04',
    authDomain: 'horas-v3-d8f04.firebaseapp.com',
    storageBucket: 'horas-v3-d8f04.firebasestorage.app',
    measurementId: 'G-5G15Y3ZJK5',
  );

}